version: '3.5'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    hostname: mssql
    container_name: mssql
    networks: 
      - net
    ports:
      - 1433:1433    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3@e4r5t

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    networks: 
      - net
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    networks: 
      - net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      LISTENERS: PLAINTEXT://kafka:29092
  
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongoDB    
    networks: 
      - net
    ports:
      - 27017:27017   
    environment:            
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: MongoDB2020!
      MONGODB_DATABASE: product_stack_query      
    
  mongo-express:
    image: mongo-express
    hostname: mongoExpress
    container_name: mongoExpress    
    depends_on:
      - mongo
    networks: 
      - net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongoUser
      ME_CONFIG_BASICAUTH_PASSWORD: 1q2w3!e4r5t
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
         
networks: 
  net:
    driver: bridge